# Generated by Django 3.1.4 on 2020-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='field',
            field=models.CharField(default='field', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
